### ISSUE TITLE
Add preview button

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-siteconfig#2]
Ala the CMS, it looks like preview was attempted at one point but never worked.

**Comment by GuySartorelli** [comment]
In Silverstripe CMS 5 you can add a preview to the siteconfig via an extension if you want, and this has been documented.

**Comment by wilr** [comment]
@GuySartorelli have you got a link to the docs for this? I think it would be great for clients to preview things ala pages.

**Comment by GuySartorelli** [comment]
https://docs.silverstripe.org/en/5/developer_guides/customising_the_admin_interface/preview/

It's just like making a normal `DataObject` in your project code previewable - the only difference is that you implement the `CMSPreviewable` interface in an extension instead of directly on the `DataObject` subclass.
