### ISSUE TITLE
Use of undefined constant CMS_DIR when not install with CMS

### ISSUE THREAD

**Issue by hutlim** [silverstripe/silverstripe-siteconfig#44]
It's prompt a notice if I'm install with framework only. 

`Requirements::javascript(CMS_DIR . '/client/dist/js/bundle.js');`

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-siteconfig/pull/45

**Comment by hutlim** [comment]
this fix not in branch 3.5 ?

**Comment by tractorcow** [comment]
3.5 doesn't have bundle.js does it?

**Comment by hutlim** [comment]
nope.
but it use 
`Requirements::javascript(CMS_DIR . '/javascript/CMSMain.EditForm.js');`

**Comment by tractorcow** [comment]
I guess we should make cms a dependency of this module then?

**Comment by dhensby** [comment]
or just wrap in an `if (defined())`

**Comment by Zauberfisch** [comment]
Did someone investigate why we need EditForm.js?

From what I can tell it's the only thing that relates to the CMS within SiteConfig. And just setting CMS_DIR to an empty string in my mysite/_config.php (which means Requirements will just not find the file) did not have any noticeable bad side effects.

Adding CMS as a dependency feels like a bad idea. The whole point of separating CMS and SiteConfig is so you can use it separately, at least in my opinion.

**Comment by kinglozzer** [comment]
@Zauberfisch at a glance, because it includes JS for the toggles on “Who can view this site” etc. It should just be a case of taking that code out of CMS and adding it to this module instead I think

**Comment by Zauberfisch** [comment]
Ah, right. Because my site doesn't use this feature, I didn't notice it breaking.

Well, looking into it myself now, I am starting to wonder if this "Who can view sites on this website" stuff actually belongs inside SiteConfig. Because from what I can tell, SIteConfig itself never uses those permission settings. SiteConfig edit permissions are actually handled via Members/Groups. And this permissions here are solely designed to handle permissions of SiteTree objects.

Therefore I would like to propose to strip the Access Tab and all associated features from SiteConfig and move it into a SiteConfigExtension that resides in the CMS module.


PS: As for semver, I think this can be classified as a FIX rather than an API CHANGE because as it stands right now, the only API we are breaking is one that was never working in the first place. Therefore this plan should be merge-able into 3.5.x in my opinion.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
